name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:    # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予 Action 写权限以推送代码

    steps:
      # 检出 forked 仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整的提交历史以便合并

      # 配置 Git 用户信息


      - name: Configure Git
        run: |
          git config user.name "guorong"
          git config user.email "guorong2705@foxmail.com"

      # 添加上游仓库
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/jeequan/jeepay.git
          git fetch upstream

      # 合并上游仓库的更改
      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories
        continue-on-error: true  # 如果合并冲突，允许继续执行

      # 推送更改到 forked 仓库
      - name: Push changes
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
